apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.appName }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.appName }}
  template:
    metadata:
      labels:
        app: ${{ values.appName }}
    spec:
      serviceAccountName: ${{ values.appName }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
        - name: ${{ values.appName }}
          image: ${{ values.imageRepository }}:${{ values.imageTag }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: ${{ values.appName }}-db-creds
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
