apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.namespace }}-prod
resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: ${{ values.appName }}
    patch: |-
      - op: replace
        path: /spec/replicas
        value: ${{ values.prodReplicaCount }}
  - target:
      kind: DBInstance
      name: ${{ values.appName }}-db
    patch: |-
      - op: replace
        path: /spec/dbInstanceClass
        value: ${{ values.dbInstanceClass }}
      - op: replace
        path: /spec/allocatedStorage
        value: ${{ values.dbStorageGb }}
      - op: replace
        path: /spec/multiAZ
        value: true
      - op: replace
        path: /spec/deletionProtection
        value: true
