apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.namespace }}-prod
resources:
  - ../../base

patches:
  - target:
      kind: Rollout
      name: ${{ values.appName }}
    patch: |-
      - op: replace
        path: /spec/replicas
        value: ${{ values.prodReplicaCount }}
      - op: replace
        path: /spec/strategy/blueGreen/autoPromotionEnabled
        value: false
      - op: replace
        path: /spec/strategy/blueGreen/scaleDownDelaySeconds
        value: 300
