apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.namespace }}
resources:
  - serviceaccount.yaml
  - rollout.yaml
  - active-service.yaml
  - preview-service.yaml
  - keycloak-client.yaml
  - oidc-client-secret.yaml
  - networkpolicy.yaml
