apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.namespace }}-staging
resources:
  - ../../base

patches:
  - target:
      kind: Rollout
      name: ${{ values.appName }}
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/strategy/blueGreen/autoPromotionEnabled
        value: true
      - op: replace
        path: /spec/strategy/blueGreen/scaleDownDelaySeconds
        value: 60
